semi: false
singleQuote: true
tabWidth: 2
trailingComma: es5
plugins:
  - "@ianvs/prettier-plugin-sort-imports"
importOrder:
  - "^react$"
  - "^react-dom$"
  - "<THIRD_PARTY_MODULES>"
  - ""
  - "^~/(.*)$"
  - "^\\./(.*)$"
importOrderParserPlugins:
  - typescript
  - jsx
  - decorators-legacy
importOrderTypeScriptVersion: "5.2.2"
